version: '3.7'

x-node_env: &node_env
  NODE_ENV: dev

services:
  web:
    environment: *node_env
    command: ['yarn', 'start']
    volumes:
      - ../../web:/app
      - /app/node_modules

  api:
    environment: *node_env
    command: [sh, -c, 'yarn mig:checkdb && yarn start']
    volumes:
      - ../../api:/app
      - /app/node_modules
    expose:
      - '9229' # Debug port
    ports:
      - '9229:9229' # Debug port

  end2end:
    environment: *node_env
    image: scratch
