version: '3.7'

x-node_env: &node_env
  NODE_ENV: dev

services:
  web:
    environment: *node_env

  api:
    environment: *node_env
    command: [sh, -c, 'yarn mig:checkdb && yarn start']

  end2end:
    environment: *node_env
    image: scratch
