version: '3'
services:
  web:
    image: wtrips-web:dev
    build:
      context: ../../web/
      dockerfile: ./docker/dev/Dockerfile
    environment:
      - REACT_APP_API_ENDPOINT=${API_HOST}:${API_PORT}/api
      - PORT=${WEB_PORT}
    env_file:
      - .env
    volumes:
      - ../../:/app
      - /app/web/node_modules
    expose:
      - '${WEB_PORT}'
    ports:
      - '${WEB_PORT}:${WEB_PORT}'
    depends_on:
      - api
    stdin_open: true
    tty: true

  api:
    image: wtrips-api:dev
    build:
      context: ../../api/
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - .env
    volumes:
      - ../../:/app
      - /app/api/node_modules
    expose:
      - '${API_PORT}'
    ports:
      - '${API_PORT}:${API_PORT}'
    links:
      - postgres
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  postgres:
    image: postgres:10.5-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
