version: '3.7'

services:
  web:
    image: wtrips-web:dev
    build:
      context: ../../web/
      dockerfile: ./docker/dev/Dockerfile
    environment:
      PORT: ${WEB_PORT}
      API_HOST: http://api:${API_PORT}/
    env_file:
      - .env
    command: ['yarn', 'start']
    volumes:
      - ../../:/app
      - /app/web/node_modules
    expose:
      - '${WEB_PORT}'
    ports:
      - '${WEB_PORT}:${WEB_PORT}'
    depends_on:
      - api
    stdin_open: true
    tty: true

  api:
    image: wtrips-api:dev
    build:
      context: ../../api/
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - .env
    command: ['yarn', 'start']
    volumes:
      - ../../:/app
      - /app/api/node_modules
    expose:
      - '${API_PORT}'
      - '9229' # Debug port
    ports:
      - '${API_PORT}:${API_PORT}'
      - '9229:9229' # Debug port
    links:
      - postgres
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  postgres:
    image: postgres:10.5-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
    expose:
      - '${DB_PORT}'
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  end2end:
    image: wtrips-end2end
    build:
      context: ../../end2end/
      dockerfile: ./docker/Dockerfile
    environment:
      CYPRESS_BASE_URL: http://web:${WEB_PORT}
    volumes:
      - ../../end2end:/end2end
      - /end2end/node_modules
    links:
      - web
    depends_on:
      - web
    stdin_open: true
    tty: true

volumes:
  postgres-data: {}
