version: 2

defaults: &defaults
  machine: true
  working_directory: ~/repo

update_docker: &update_docker
  name: 'Update Docker'
  command: |
    docker --version
    sudo apt-get update
    sudo apt-get install docker-ce
    docker --version

update_docker_compose: &update_docker_compose
  name: 'Update Docker Compose'
  command: |
    docker-compose --version    
    sudo curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    docker-compose --version

jobs:
  unit_tests:
    <<: *defaults
    steps:
      - checkout

      - run:
          <<: *update_docker

      - run:
          <<: *update_docker_compose

      - run:
          name: Build Docker Images (Test Env)
          command: |
            env > ./docker/test/.env
            docker pull walmor/wtrips-api:latest-dev
            npm run dc:test build

      - run:
          name: Run Unit Tests
          command: npm run dc:test:run-test

  e2e_tests:
    <<: *defaults
    steps:
      - checkout

      - run:
          <<: *update_docker

      - run:
          <<: *update_docker_compose

      - run:
          name: Build Docker Images (Release Env)
          command: |
            env
            env > ./docker/release/.env
            npm run dc:rel build

      - run:
          name: Run E2E Tests
          command: npm run dc:rel:run-e2e

tag_filter: &tag_filter
  branches:
    # ignore any commit on any branch by default
    ignore: /.*/
  tags:
    # only act on version tags
    only: /^v[0-9]+(\.[0-9]+)*(-\w+\.[0-9]+)?$/

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - unit_tests:
          filters:
            branches:
              only: circleci #test
      # - e2e_tests:
      #     filters:
      #       branches:
      #         only: circleci #test
